export const ADD_NOTE_TO_PHRASE = 'ADD_NOTE_TO_PHRASE';
export const TOGGLE_ALL_PHRASE = 'TOGGLE_ALL_PHRASE';
export const SELECT_ONE_PHRASE = 'SELECT_ONE_PHRASE';
export const UNSELECT_ALL_PHRASE = 'UNSELECT_ALL_PHRASE';
