export const ADD_NOTE_TO_PHRASE = 'ADD_NOTE_TO_PHRASE';
export const TOGGLE_ALL_PHRASE = 'TOGGLE_ALL_PHRASE';
export const SELECT_ONE_PHRASE = 'SELECT_ONE_PHRASE';
export const HIDE_SELECTED_PHRASE = 'HIDE_SELECTED_PHRASE';
export const SET_SELECTED_PHRASE_VISIBLE = 'SET_SELECTED_PHRASE_VISIBLE';
export const UPDATE_DISPLAYING_PHRASE_TYPE = 'UPDATE_DISPLAYING_PHRASE_TYPE';
